# -*- coding: utf-8 -*-
"""streamlit450.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x-jwDE8pCA9lpKvHNUoV9OWA-z9M3QHQ
"""

import streamlit as st
import pandas as pd
import plotly.express as px
df=pd.read_csv('Advertising_F.csv')

st.title("Advertising Effectiveness Dashboard")
st.sidebar.header("Filters")
x_var=st.sidebar.selectbox("X-Axis",['TV','radio','newspaper'])
y_var=st.sidebar.selectbox("Y-Axis",['sales'])

fig=px.scatter(df,x='TV',y='radio')
st.plotly_chart(fig)

st.write('### Data Frame')
st.dataframe(df)

st.title("I AM THE MAP!!!")
fig=px.scatter_mapbox(df,lat='latitude',lon='longitude',size='newspaper',hover_name='City',
                      color='sales',color_continuous_scale=px.colors.sequential.Viridis)
fig.update_layout(mapbox_style='carto-positron')
st.plotly_chart(fig)

